const express = require("express");
const router = express.Router();
const {
  BUILDINGHEADWISEREPORT,
  DPDCHEADWISEREPORT,
  SHDORHEADWISEREPORT,
  NABARDHEADWISEREPORT,
  CRFHEADWISEREPORT,
  MASTERHEADWISEREPOSTBuilding,
  MASTERHEADWISEREPOSTRoad,
  MASTERHEADWISEREPOSTCRF,
  MASTERHEADWISEREPOSTNabard,
  MASTERHEADWISEREPOSTAnnuity,
  MASTERHEADWISEREPOST2515,
  MASTERHEADWISEREPOSTDepositeFund,
  MASTERHEADWISEREPOSTDPDC,
  MASTERHEADWISEREPOSTGatA,
  MASTERHEADWISEREPOSTGatD,
  MASTERHEADWISEREPOSTGatFBC,
  MASTERHEADWISEREPOSTMLA,
  MASTERHEADWISEREPOSTMP,
  MASTERHEADWISEREPOSTNRB,
  MASTERHEADWISEREPOSTRB
} = require("../controllers/masterHeadWiseController");

// Route to get upcoming due dates (next 20 days)
router.post("/BUILDINGHEADWISEREPORT", BUILDINGHEADWISEREPORT);
router.post("/DPDCHEADWISEREPORT", DPDCHEADWISEREPORT);
router.post("/SHDORHEADWISEREPORT", SHDORHEADWISEREPORT);
router.post("/NABARDHEADWISEREPORT", NABARDHEADWISEREPORT);
router.post("/CRFHEADWISEREPORT", CRFHEADWISEREPORT);

//Master Individual report routes
router.post("/MASTERHEADWISEREPOSTBuilding", MASTERHEADWISEREPOSTBuilding);
router.post("/MASTERHEADWISEREPOSTRoad", MASTERHEADWISEREPOSTRoad);
router.post("/MASTERHEADWISEREPOSTCRF", MASTERHEADWISEREPOSTCRF);
router.post("/MASTERHEADWISEREPOSTNabard", MASTERHEADWISEREPOSTNabard);
router.post("/MASTERHEADWISEREPOSTAnnuity", MASTERHEADWISEREPOSTAnnuity);
router.post("/MASTERHEADWISEREPOST2515", MASTERHEADWISEREPOST2515);
router.post("/MASTERHEADWISEREPOSTDepositeFund", MASTERHEADWISEREPOSTDepositeFund);
router.post("/MASTERHEADWISEREPOSTDPDC", MASTERHEADWISEREPOSTDPDC);
router.post("/MASTERHEADWISEREPOSTGatA", MASTERHEADWISEREPOSTGatA);
router.post("/MASTERHEADWISEREPOSTGatD", MASTERHEADWISEREPOSTGatD);
router.post("/MASTERHEADWISEREPOSTGatFBC", MASTERHEADWISEREPOSTGatFBC);
router.post("/MASTERHEADWISEREPOSTMLA", MASTERHEADWISEREPOSTMLA);
router.post("/MASTERHEADWISEREPOSTMP", MASTERHEADWISEREPOSTMP);
router.post("/MASTERHEADWISEREPOSTNRB", MASTERHEADWISEREPOSTNRB);
router.post("/MASTERHEADWISEREPOSTRB", MASTERHEADWISEREPOSTRB);




module.exports = router;
